"""
Prompt extraction via LLM — reads tweets from DB, calls LLM API for each tweet,
classifies prompts, manages dynamic Category library with human-in-the-loop.

Usage:
    python scripts/extract_prompts.py
    python scripts/extract_prompts.py --scrape-id 3
    python scripts/extract_prompts.py --output outputs/prompts.json
"""

import sys
from pathlib import Path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

import argparse
import json
import os
import time as _time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from threading import Lock
from typing import Optional

from dotenv import load_dotenv
load_dotenv()

import requests

from scripts.db import (
    init_db,
    get_categories,
    get_pending_suggestions,
    suggest_category,
    approve_suggestion,
    reject_suggestion,
    insert_prompts,
    get_recent_tweets,
    get_tweets_without_prompts,
    update_scrape_query_stats,
    get_scrape_query_stats,
    count_prompts_for_scrape,
    get_prompts_for_scrape_by_query,
)

DEFAULT_INPUT = PROJECT_ROOT / "outputs" / "raw_tweets.json"
DEFAULT_OUTPUT = PROJECT_ROOT / "outputs" / "prompts.json"
DEFAULT_MODEL = "MiniMax-M2.7"
DEFAULT_CONCURRENCY = 15

# Keywords that suggest a prompt is embedded in the tweet text
PROMPT_INDICATORS = [
    "prompt:", "\nPrompt ", "\"prompt\":", "prompt_details",
    "见评论", "评论区", "prompt in", "prompt below",
]


def should_recheck(text: str) -> bool:
    """Return True if tweet text contains prompt indicators that warrant a second review."""
    t = text.lower()
    return any(kw in t for kw in PROMPT_INDICATORS)


def build_system_prompt(categories: list[dict]) -> str:
    """Build category-aware system prompt with active categories."""
    cat_names = ", ".join(c["name"] for c in categories)
    return (
        f"You are a prompt extraction specialist for AI VIDEO and IMAGE GENERATION.\n"
        f"STRICT CRITERIA — only mark is_prompt=true when ALL of these are true:\n"
        f"  1. The prompt describes visual content that can be directly generated by Veo/Gemini (video clips, images, 3D renders, product photography, cinematic scenes, character designs, etc.)\n"
        f"  2. The prompt contains enough detail to GUIDE actual generation (camera angles, lighting, motion, composition, subject description, style keywords, etc.)\n"
        f"  3. The output is visual/media, NOT plain text, code, documentation, or conversation\n\n"
        f"Mark is_prompt=false for:\n"
        f"  - Code generation, CLI tools, software architecture prompts (e.g. 'act as a principal engineer...')\n"
        f"  - Plain text assistants, writing tasks, brainstorming prompts\n"
        f"  - Non-visual analysis tasks (code review, debugging, document writing)\n"
        f"  - Anything whose primary output is text rather than visual media\n\n"
        f"Respond with valid JSON only, no markdown, no explanation: "
        f'{{"is_prompt": true or false, '
        f'"category": "{cat_names}" | "other" | null, '
        f'"title": "short title" or null, '
        f'"prompt_text": "text" or null, '
        f'"notes": "note" or null}}. '
        f"If the category does not match any existing category, use 'other'. "
        f"If it is not a prompt at all, set is_prompt=false."
    )


def call_llm(
    text: str,
    api_base: str,
    api_key: str,
    model: str,
    system_prompt: str,
    timeout: int = 60,
) -> Optional[dict]:
    url = f"{api_base.rstrip('/')}/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Tweet:\n{text}"},
        ],
        "temperature": 0.0,
        "max_tokens": 500,
    }
    try:
        resp = requests.post(url, headers=headers, json=payload, timeout=timeout)
        if resp.status_code != 200:
            return None
        raw = resp.json()["choices"][0]["message"]["content"]
        json_text = raw
        last_brace = json_text.rfind("}")
        first_brace = json_text.find("{")
        if first_brace != -1 and last_brace != -1 and last_brace >= first_brace:
            json_text = json_text[first_brace : last_brace + 1]
        return json.loads(json_text)
    except (json.JSONDecodeError, KeyError, TypeError):
        return None


def recheck_tweet(tweet: dict, api_base: str, api_key: str, model: str) -> Optional[dict]:
    """
    Second-pass review for tweets that were flagged as 'not a prompt' but contain
    prompt indicators (e.g., 'Prompt:', '见评论', etc.).

    Strict: only returns a result if the tweet itself contains a usable Veo prompt.
    If the tweet just references 'prompt in comments' without providing content, returns None.
    """
    RECHECK_PROMPT = (
        "You are a Veo video generation prompt reviewer.\n"
        "A tweet was initially flagged as not containing a prompt.\n"
        "However, the tweet text contains keywords that suggest a prompt may be present.\n\n"
        "IMPORTANT: Be STRICT. Only return JSON if the tweet ITSELF contains a complete,\n"
        "directly usable prompt for Veo/Gemini video generation.\n"
        "If the tweet only says 'prompt in comments', 'see reply', 'prompt below',\n"
        "or references a prompt elsewhere without giving the content — return null.\n\n"
        'Reply with: {"is_prompt": true/false, "category": "...", "title": "...", '
        '"prompt_text": "...", "notes": "..."} or null.'
    )
    return call_llm(tweet.get("text", ""), api_base, api_key, model, RECHECK_PROMPT)


def process_tweet(
    tweet: dict,
    api_base: str,
    api_key: str,
    model: str,
    system_prompt: str,
) -> tuple[dict, bool, Optional[dict]]:
    """Returns (prompt_dict, was_extracted, category_suggestion_or_None)."""
    text = tweet.get("text", "")
    result = call_llm(text, api_base, api_key, model, system_prompt)

    # If LLM said not a prompt, check if recheck is warranted
    if result is None or not result.get("is_prompt", False):
        if should_recheck(text):
            result = recheck_tweet(tweet, api_base, api_key, model)
        if result is None or not result.get("is_prompt", False):
            return None, False, None

    category = result.get("category", "other")
    prompt_dict = {
        "tweet_id":   tweet.get("tweet_id", ""),
        "url":        tweet.get("url", ""),
        "category":   category,
        "title":      result.get("title", ""),
        "prompt_text": result.get("prompt_text", ""),
        "notes":      result.get("notes", ""),
        "author": {
            "name":          tweet.get("author_name", ""),
            "screen_name":   tweet.get("author_screen", ""),
            "followers_count": tweet.get("followers_count", 0),
        },
        "engagement": {
            "likes":    tweet.get("favorite_count", 0),
            "retweets": tweet.get("retweet_count", 0),
            "replies":  tweet.get("reply_count", 0),
            "views":    tweet.get("view_count", 0),
        },
    }
    return prompt_dict, True, None


def collect_new_category_suggestions(
    prompts: list[dict],
    known_categories: set[str],
    api_key: str,
    api_base: str,
    model: str,
) -> list[dict]:
    """Check prompts for new categories not in known list, ask LLM for descriptions."""
    new_cat_prompts = [p for p in prompts if p["category"] not in known_categories]
    if not new_cat_prompts:
        return []

    suggestions = []
    for p in new_cat_prompts:
        reason = (
            f"Tweet @{p.get('author',{}).get('screen_name','?')} "
            f"classified as '{p['category']}' but this category is not in DB. "
            f"Prompt: {p.get('prompt_text','')[:100]}"
        )
        sug_id = suggest_category(
            name=p["category"],
            reason=reason,
            prompt_text=p.get("text", "") or p.get("prompt_text", ""),
            suggested_by=model,
            description="",
        )
        suggestions.append({"id": sug_id, "name": p["category"], "reason": reason})
    return suggestions


def handle_new_categories(
    prompts: list[dict],
    known_categories: set[str],
    api_key: str,
    api_base: str,
    model: str,
) -> list[dict]:
    """Check prompts for unknown categories, pause and ask user for each one."""
    new_cat_prompts = [p for p in prompts if p["category"] not in known_categories]
    if not new_cat_prompts:
        return prompts

    # Group by category name
    from collections import defaultdict
    grouped = defaultdict(list)
    for p in new_cat_prompts:
        grouped[p["category"]].append(p)

    for cat_name, cat_prompts in grouped.items():
        sample = cat_prompts[0]
        print(f"\n[NEW]  New category detected: '{cat_name}'")
        print(f"   Sample prompt: {sample.get('prompt_text','')[:100]}...")
        print(f"   From: @{sample.get('author',{}).get('screen_name','?')}")
        print(f"   Total tweets with this category: {len(cat_prompts)}")
        print()
        print(f"Options:")
        print(f"  [y] Approve — add '{cat_name}' to categories")
        print(f"  [n] Reject  — mark as 'other', don't add category")
        print(f"  [r] Rename  — type new name to replace '{cat_name}'")
        choice = input("Your choice [y/n/r]: ").strip().lower()

        if choice == "y":
            approve_suggestion(suggest_category(
                name=cat_name,
                reason=f"Approved manually. {len(cat_prompts)} tweets.",
                prompt_text=sample.get("prompt_text", ""),
                suggested_by=model,
            ))
            print(f"  [OK] Category '{cat_name}' added.")
        elif choice == "r":
            new_name = input(f"  New category name: ").strip()
            if new_name:
                approve_suggestion(suggest_category(
                    name=new_name,
                    reason=f"Renamed from '{cat_name}' manually.",
                    prompt_text=sample.get("prompt_text", ""),
                    suggested_by=model,
                ))
                print(f"  ✓ Category '{new_name}' added.")
                # Update prompts with new category
                for p in cat_prompts:
                    p["category"] = new_name
        else:
            print(f"  [REJECTED] Category '{cat_name}' rejected — tweets will use 'other'.")
            for p in cat_prompts:
                p["category"] = "other"

    return prompts


def extract_prompts(
    input_path: Path,
    output_path: Path,
    api_base: Optional[str],
    api_key: Optional[str],
    model: str,
    concurrency: int = DEFAULT_CONCURRENCY,
    scrape_id: int = None,
) -> list[dict]:
    init_db()

    # Check pending suggestions first
    pending = get_pending_suggestions()
    if pending:
        print(f"\n[WARN] {len(pending)} pending category suggestion(s) in DB:")
        for s in pending:
            print(f"  [{s['id']}] '{s['suggested_name']}' — {s['reason'][:80]}...")
        print("\nReview them before continuing? [y] to review, [Enter] to skip:")
        if input("> ").strip().lower() == "y":
            for s in pending:
                print(f"\nSuggestion: '{s['suggested_name']}'")
                print(f"  Reason: {s['reason']}")
                print(f"  Prompt: {s['prompt_text'][:100]}...")
                print(f"  [a]pprove  [r]eject  [s]kip")
                c = input("> ").strip().lower()
                if c == "a":
                    approve_suggestion(s["id"])
                    print("  [OK] Approved")
                elif c == "r":
                    reject_suggestion(s["id"])
                    print("  [REJECTED] Rejected")
                else:
                    print("  Skipped")
            print()

    # Load tweets from DB — incremental: only tweets without a prompt entry
    if input_path and input_path.exists():
        with open(input_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        tweets = data.get("tweets", [])
    else:
        tweets = get_tweets_without_prompts()
        if scrape_id is not None:
            from scripts.db import get_tweets_for_scrape
            tweets = get_tweets_for_scrape(scrape_id)

    total = len(tweets)
    print(f"Loaded {total} tweets for processing")
    if not tweets:
        return []

    api_base = api_base or os.environ.get("OPENAI_API_BASE", "https://api.minimaxi.com/v1")
    api_key = api_key or os.environ.get("OPENAI_API_KEY", "")
    if not api_key:
        print("ERROR: OPENAI_API_KEY not set. Create .env from .env.example.")
        sys.exit(1)

    categories = get_categories()
    known_cat_names = {c["name"] for c in categories}
    system_prompt = build_system_prompt(categories)
    print(f"Active categories: {list(known_cat_names)}")
    print(f"Concurrency: {concurrency}")

    prompts = []
    done = 0
    lock = Lock()
    suggestion_lock = Lock()

    def on_result(wid, tweet, result_tuple):
        nonlocal done, prompts
        prompt_dict, was_extracted, _ = result_tuple
        with lock:
            done += 1
            screen = tweet.get("author_screen", "?")
            if was_extracted:
                print(f"[{done}/{total}] @{screen} EXTRACTED [{prompt_dict['category']}] {prompt_dict['title']}")
                prompts.append(prompt_dict)
            else:
                print(f"[{done}/{total}] @{screen} skipped")

    with ThreadPoolExecutor(max_workers=concurrency) as ex:
        futures = {}
        for i, tweet in enumerate(tweets):
            screen = tweet.get("author_screen", "?")
            print(f"  Queuing [{i+1}/{total}] @{screen}...")
            fut = ex.submit(
                process_tweet, tweet, api_base, api_key, model, system_prompt
            )
            futures[fut] = (i, tweet)

        for fut in as_completed(futures):
            i, tweet = futures[fut]
            try:
                result_tuple = fut.result()
            except Exception:
                result_tuple = (None, False)
            on_result(i, tweet, result_tuple)

    # Check for new categories and handle them
    prompts = handle_new_categories(prompts, known_cat_names, api_key, api_base, model)

    # Save to DB
    db_scrape_id = scrape_id if scrape_id else 1  # default scrape if none
    insert_prompts(db_scrape_id, prompts)

    # Backfill prompt counts into query_stats
    if db_scrape_id:
        try:
            query_stats = get_scrape_query_stats(db_scrape_id)
            if query_stats:
                # Count prompts by source query
                prompts_by_query = get_prompts_for_scrape_by_query(db_scrape_id)
                updated = False
                for q, cnt in prompts_by_query.items():
                    if q in query_stats:
                        query_stats[q]["prompts"] = cnt
                        updated = True
                if updated:
                    update_scrape_query_stats(db_scrape_id, query_stats)
                    print(f"  Updated query_stats with prompt counts: {prompts_by_query}")
        except Exception as e:
            print(f"  Could not update query_stats: {e}")

    print(f"\nExtracted {len(prompts)} prompts from {total} tweets")

    # Save JSON export
    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        cats = {}
        for p in prompts:
            cats[p["category"]] = cats.get(p["category"], 0) + 1
        export = {
            "extract_time": datetime.now(timezone.utc).isoformat(),
            "llm_model": model,
            "concurrency": concurrency,
            "total_input": total,
            "total_extracted": len(prompts),
            "categories": cats,
            "prompts": prompts,
        }
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(export, f, ensure_ascii=False, indent=2)
        print(f"JSON export saved to {output_path}")

    return prompts


# ─── CLI ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Extract prompts from DB tweets via LLM (concurrent, with Category management)"
    )
    parser.add_argument("--input",      type=str, default=None,
                        help="Input JSON (legacy, use --scrape-id for DB mode)")
    parser.add_argument("--scrape-id",  type=int, default=None,
                        help="Process tweets from a specific scrape ID in DB")
    parser.add_argument("--output",     type=str, default=str(DEFAULT_OUTPUT),
                        help="Output JSON path")
    parser.add_argument("--api-base",   type=str, default=None,
                        help="API base URL (or OPENAI_API_BASE env var)")
    parser.add_argument("--api-key",    type=str, default=None,
                        help="API key (or OPENAI_API_KEY env var)")
    parser.add_argument("--model",       type=str, default=DEFAULT_MODEL,
                        help=f"LLM model (default: {DEFAULT_MODEL})")
    parser.add_argument("--concurrency", type=int, default=DEFAULT_CONCURRENCY,
                        help=f"Parallel LLM calls (default: {DEFAULT_CONCURRENCY})")
    args = parser.parse_args()

    input_path = Path(args.input) if args.input else None
    output_path = Path(args.output)

    print("=" * 60)
    print("Prompt Extraction via LLM (Concurrent + Category Management)")
    print("=" * 60)
    print(f"  Input:       {input_path or 'from DB (recent tweets)'}")
    print(f"  Scrape ID:  {args.scrape_id or 'most recent'}")
    print(f"  Output:     {output_path}")
    print(f"  Model:      {args.model}")
    print(f"  Concurrency: {args.concurrency}")
    print(f"  API:        {args.api_base or 'from env'}")
    print("=" * 60 + "\n")

    extract_prompts(
        input_path=input_path,
        output_path=output_path,
        api_base=args.api_base,
        api_key=args.api_key,
        model=args.model,
        concurrency=args.concurrency,
        scrape_id=args.scrape_id,
    )


if __name__ == "__main__":
    main()
